package com.papaya.cycleactivitylog.service.apis.v1.responses;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.NonNull;

import java.time.LocalDateTime;

@Data
public class LoggedItemResponse {
    @Schema(example = "1", description = "Cycle id of the item")
    private final @NonNull String cycleId;

    @Schema(example = "a1b2c3d4e5", description = "Hash of the item. For each cycleId, the hash is unique.")
    private final @NonNull String hash;

    @Schema(example = "2000-01-01T01:01:01:001", description = "When the item was logged")
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS")
    private final @NonNull LocalDateTime when;

    @Schema(example = "2000-01-01T01:01:01:001", description = "When the item occurred")
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS")
    private final @NonNull LocalDateTime occurrence;

    @Schema(example = "GOV", description = "Source of the item")
    private final @NonNull String source;

    @Schema(example = "GET_TIMELINE", description = "Event of the item")
    private final @NonNull String event;

    @Schema(example = "Payroll", description = "State of the item")
    private final String state;

    @Schema(example = "Info", description = "Severity of the item")
    private final @NonNull LoggedItemSeverity severity;

    @Schema(example = "Business", description = "Event type of the item")
    private final @NonNull LoggedItemEventType eventType;

    @Schema(example = "A user", description = "The user that generated the item or null if was generated by the system")
    private final String user;

    @Schema(example = "A summary", description = "Summary of the item")
    private final String summary;

}

